# Generated by Django 3.0.4 on 2020-03-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='no')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('category', models.CharField(blank=True, choices=[('0', 'シューター'), ('1', 'マニューバー'), ('2', 'ブラスター'), ('3', 'スピナー'), ('4', 'ローラー'), ('5', 'フデ'), ('6', 'チャージャー'), ('7', 'スロッシャー'), ('8', 'シェルター'), ('9', 'ガイザー')], max_length=2)),
                ('gauge', models.IntegerField(blank=True, null=True, verbose_name='gauge')),
                ('release_condition', models.CharField(blank=True, max_length=100, verbose_name='release_condition')),
                ('range', models.IntegerField(blank=True, null=True, verbose_name='range')),
                ('continuous_power', models.IntegerField(blank=True, null=True, verbose_name='continuous_power')),
                ('fixed_num', models.IntegerField(blank=True, null=True, verbose_name='fixed_num')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
            options={
                'verbose_name': 'ブキ',
                'verbose_name_plural': 'ブキ一覧',
            },
        ),
    ]
